package com.bumptech.glide.annotation.compiler;

import com.bumptech.glide.annotation.GlideType;
import com.google.auto.service.AutoService;
import java.util.HashSet;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;

// Links in Javadoc will work due to build setup, even though there is no direct dependency here.
/**
 * Generates classes based on Glide's annotations that configure Glide, add support for additional
 * resource types, and/or extend Glide's API.
 *
 * <p>This processor discovers all {@code AppGlideModule} and
 * {@code LibraryGlideModule} implementations that are
 * annotated with {@link com.bumptech.glide.annotation.GlideModule}. Any implementations missing the
 * annotation will be ignored.
 *
 * <p>This processor also discovers all {@link com.bumptech.glide.annotation.GlideExtension}
 * annotated classes.
 *
 * <p>Multiple classes are generated by this processor:
 * <ul>
 *   <li>For {@code LibraryGlideModule}s - A GlideIndexer class in a
 *      specific package that will later be used by the processor to discover all
 *      {@code LibraryGlideModule} classes.
 *   <li>For {@code AppGlideModule}s - A single
 *      {@code AppGlideModule} implementation
 *     ({@code com.bumptech.glide.GeneratedAppGlideModule}) that calls all
 *     {@code LibraryGlideModule}s and the
 *     original {@code AppGlideModule} in the correct order when Glide is
 *     initialized.
 *   <li>{@link com.bumptech.glide.annotation.GlideExtension}s -
 *   <ul>
 *     <li>A {@code com.bumptech.glide.request.RequestOptions} implementation that contains
 *     static versions of all builder methods in the base class and both static and instance
 *     versions of methods in all {@link com.bumptech.glide.annotation.GlideExtension}s.
 *     <li>If one or more methods in one or more
 *     {@link com.bumptech.glide.annotation.GlideExtension} annotated classes are annotated with
 *     {@link GlideType}:
 *     <ul>
 *       <li>A {@code com.bumptech.glide.RequestManager} implementation containing a generated
 *       method for each method annotated with
 *       {@link GlideType}.
 *       <li>A {@code com.bumptech.glide.manager.RequestManagerRetriever.RequestManagerFactory}
 *       implementation that produces the generated {@code com.bumptech.glide.RequestManager}s.
 *       <li>A {@code com.bumptech.glide.Glide} look-alike that implements all static methods in
 *       the {@code com.bumptech.glide.Glide} singleton and returns the generated
 *       {@code com.bumptech.glide.RequestManager} implementation when appropriate.
 *     </ul>
 *   </ul>
 * </ul>
 *
 * <p>{@code AppGlideModule} implementations must only be included in
 * applications, not in libraries. There must be exactly one
 * {@code AppGlideModule} implementation per
 * Application. The {@code AppGlideModule} class is
 * used as a signal that all modules have been found and that the final merged
 * {@code com.bumptech.glide.GeneratedAppGlideModule} impl can be created.
 */
@AutoService(Processor.class)
public final class GlideAnnotationProcessor extends AbstractProcessor {
  static final boolean DEBUG = false;
  private ProcessorUtil processorUtil;
  private LibraryModuleProcessor libraryModuleProcessor;
  private AppModuleProcessor appModuleProcessor;
  private boolean isGeneratedAppGlideModuleWritten;
  private ExtensionProcessor extensionProcessor;

  @Override
  public synchronized void init(ProcessingEnvironment processingEnvironment) {
    super.init(processingEnvironment);
    //注解处理器工具类定义
    processorUtil = new ProcessorUtil(processingEnvironment);
    //包含一/多个LibraryGlideModules or GlideExtensions的空类
    IndexerGenerator indexerGenerator = new IndexerGenerator(processorUtil);
    //LibraryModule注解生成工具类
    libraryModuleProcessor = new LibraryModuleProcessor(processorUtil, indexerGenerator);
    //注解最后一步，生成最后的类
    appModuleProcessor = new AppModuleProcessor(processingEnvironment, processorUtil);
    //生成Indexer类(Index注解)
    extensionProcessor =
        new ExtensionProcessor(processingEnvironment, processorUtil, indexerGenerator);
  }

  @Override
  public Set<String> getSupportedAnnotationTypes() {
    //声明能被处理的注解类型： GlideModule 和 GlideExtension
    Set<String> result = new HashSet<>();
    result.addAll(libraryModuleProcessor.getSupportedAnnotationTypes());
    result.addAll(extensionProcessor.getSupportedAnnotationTypes());
    return result;
  }

  @Override
  public SourceVersion getSupportedSourceVersion() {
    return SourceVersion.latestSupported();
  }

   /**
    * Each round we do the following:
    * <ol>
    *   <li>Find all {@code AppGlideModule}s and save them to an instance variable (throw if > 1).
    *   <li>Find all {@code LibraryGlideModule}s
    *   <li>For each {@code LibraryGlideModule},
    *       write an {@code Indexer} with an Annotation with the class name.
    *   <li>If we wrote any {@code Indexer}s, return and wait for the next round.
    *   <li>If we didn't write any {@code Indexer}s and there is a {@code AppGlideModule},
    *       write the {@code GeneratedAppGlideModule}.
    *       Once the {@code GeneratedAppGlideModule} is written, we expect to be finished.
    *       Any further generation of related classes will result in errors.
    * </ol>
    * 每轮干的事情：
    * 1. 找到所有{@code GlideModule} 注解的 {@code AppGlideModule}
    * 2. 找到所有{@code LibraryGlideModule}，对每个{@code LibraryGlideModule}生成一个由{@code Indexer}注解的类
    * 3. ...
    */
  @Override
  public boolean process(Set<? extends TypeElement> set, RoundEnvironment env) {
//    if (set.isEmpty() && !isGeneratedAppGlideModulePending) {
//      return false;
//    }
    //累加执行的圈数
    processorUtil.process();
    //libraryModule文件的生成
    boolean newModulesWritten = libraryModuleProcessor.processModules(env);

    boolean newExtensionWritten = extensionProcessor.processExtensions(env);
    //创建唯一的appModule
    appModuleProcessor.processModules(set, env);

    if (newExtensionWritten || newModulesWritten) {
      if (isGeneratedAppGlideModuleWritten) {
        throw new IllegalStateException("Cannot process annotations after writing AppGlideModule");
      }
      return true;
    }

    if (!isGeneratedAppGlideModuleWritten) {
      isGeneratedAppGlideModuleWritten = appModuleProcessor.maybeWriteAppModule();
    }
    return true;
  }
}
